Сверстан хедер домашней страницы
RezDmitry/speedline pull request #1
Opened 2022-07-25 14:35 UTC by RezDmitry

Сверстана шапка стартовой страницы

2022-07-25 14:51 UTC, Viktor-Web-Dev requested changes

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/common/Button/Button.tsx
> +  return (
по всей видимости тут не будет прописана дополнительная логика для этой компоненты можно заменить на 
const Button = ({children, transparent}: IButtonProps) => (
 <button className={`${styles.button} ${transparent ? styles.transparent : ''}`}>
    {children}
  </button>
);

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/App/App.tsx
> +function App() {
замени на стрелочную функцию и думаю тут ретерн не нужен

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/common/Logo/Logo.tsx
> +const Logo = () => {
...

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/layouts/AdminLayout/AdminLayout.module.scss
> +
не прописаны стили

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/layouts/AdminLayout/AdminLayout.tsx
> +    <div className={styles.container}>
<div className={styles.container} />

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/layouts/HomeLayout/HomeLayout.tsx
> +  return (
...

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/pages/home/Header/Header.tsx
> +  return (
...

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/pages/home/StartPage/StartPage.tsx
> +import Footer from "../Footer/Footer";
Давай определим порядок импорта. Смотри сначала идут библиотеки, потом компоненты с относительными путями, затем идут картинки и css. И каждый из этим пунктов отделяются ентером для более понятности что откуда берется. 
Также обрати внимание на использование ковычек они везде у тебя разные, надо бы еслинт наверное поставить

2022-07-25 14:51 UTC, Viktor-Web-Dev commented on src/components/pages/home/StartPage/StartPage.tsx
> +  return (
...

2022-07-25 14:57 UTC, RezDmitry commented on src/components/common/Button/Button.tsx
> +  return (
тут будет еще обработка кликов минимум, пока тогда сокращу запись

2022-07-25 15:02 UTC, RezDmitry commented on src/components/pages/home/StartPage/StartPage.tsx
> +import Footer from "../Footer/Footer";
понял, еслинт хотел завтра поставить

2022-07-26 08:00 UTC, Viktor-Web-Dev requested changes

2022-07-26 08:00 UTC, Viktor-Web-Dev commented on src/components/App/App.tsx
>    return (
зачем здесь return ты же просто возвращаешь разметку, тут нет никакой функциональной части

2022-07-26 08:00 UTC, Viktor-Web-Dev commented on src/components/common/Button/Button.tsx
> +);
тут лишний отступ

2022-07-26 08:00 UTC, Viktor-Web-Dev commented on src/components/layouts/HomeLayout/HomeLayout.tsx
> +
реакт ройтер дом это библиотека так что тут отступ лишний

2022-07-26 09:04 UTC, closed without merging